/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  Column,
} from './components/grid/grid-helpers';


export namespace Components {

  interface SuiDisclosure {
    /**
    * Optional override to the button's accessible name (using aria-label)
    */
    'buttonLabel': string;
    /**
    * Optionally set the popup region's accessible name using aria-label (recommended)
    */
    'popupLabel': string;
  }
  interface SuiDisclosureAttributes extends StencilHTMLAttributes {
    /**
    * Optional override to the button's accessible name (using aria-label)
    */
    'buttonLabel'?: string;
    /**
    * Emit a custom close event when the popup closes
    */
    'onClose'?: (event: CustomEvent) => void;
    /**
    * Emit a custom open event when the popup opens
    */
    'onOpen'?: (event: CustomEvent) => void;
    /**
    * Optionally set the popup region's accessible name using aria-label (recommended)
    */
    'popupLabel'?: string;
  }

  interface SuiGrid {
    /**
    * Grid data
    */
    'cells': string[][];
    /**
    * Column definitions
    */
    'columns': Column[];
    /**
    * Caption/description for the grid
    */
    'description': string;
    /**
    * String ID of labelling element
    */
    'labelledby': string;
    /**
    * Number of rows in one "page": used to compute pageUp/pageDown key behavior, and when paging is used
    */
    'pageLength': number;
    /**
    * Index of the column that best labels a row
    */
    'titleColumn': number;
  }
  interface SuiGridAttributes extends StencilHTMLAttributes {
    /**
    * Grid data
    */
    'cells'?: string[][];
    /**
    * Column definitions
    */
    'columns'?: Column[];
    /**
    * Caption/description for the grid
    */
    'description'?: string;
    /**
    * String ID of labelling element
    */
    'labelledby'?: string;
    /**
    * Emit a custom cell edit event
    */
    'onEditCell'?: (event: CustomEvent<{value: string; column: number; row: number;}>) => void;
    /**
    * Emit a custom filter event
    */
    'onFilter'?: (event: CustomEvent) => void;
    /**
    * Emit a custom row selection event
    */
    'onRowSelect'?: (event: CustomEvent) => void;
    /**
    * Number of rows in one "page": used to compute pageUp/pageDown key behavior, and when paging is used
    */
    'pageLength'?: number;
    /**
    * Index of the column that best labels a row
    */
    'titleColumn'?: number;
  }
}

declare global {
  interface StencilElementInterfaces {
    'SuiDisclosure': Components.SuiDisclosure;
    'SuiGrid': Components.SuiGrid;
  }

  interface StencilIntrinsicElements {
    'sui-disclosure': Components.SuiDisclosureAttributes;
    'sui-grid': Components.SuiGridAttributes;
  }


  interface HTMLSuiDisclosureElement extends Components.SuiDisclosure, HTMLStencilElement {}
  var HTMLSuiDisclosureElement: {
    prototype: HTMLSuiDisclosureElement;
    new (): HTMLSuiDisclosureElement;
  };

  interface HTMLSuiGridElement extends Components.SuiGrid, HTMLStencilElement {}
  var HTMLSuiGridElement: {
    prototype: HTMLSuiGridElement;
    new (): HTMLSuiGridElement;
  };

  interface HTMLElementTagNameMap {
    'sui-disclosure': HTMLSuiDisclosureElement
    'sui-grid': HTMLSuiGridElement
  }

  interface ElementTagNameMap {
    'sui-disclosure': HTMLSuiDisclosureElement;
    'sui-grid': HTMLSuiGridElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
